runtime: nodejs10

env_variables:
  NODE_ENV: production

handlers:
  - url: /static
    static_dir: .next/static

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 307
